FROM python:3.10-slim-buster

ARG AIRFLOW_VERSION-2.5.0

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir apache-airflow==2.5.0

ENV AIRFLOW_HOME=/airflow
RUN useradd -ms /bin/bash -d ${AIRFLOW_HOME} airflow
RUN chown -R airflow: ${AIRFLOW_HOME}

COPY requirements.txt . 

USER airflow
WORKDIR ${AIRFLOW_HOME}

CMD ["airflow", "webserver"]
